// Voice-over hand-off: docs/voice/lines.json is the source of truth for every spoken line.
//   node tools/voice_script.mjs          check lines.json against src/game/story.js, then write docs/voice/SCRIPT.md
//   node tools/voice_script.mjs --check  check only (exit 1 on any mismatch)
// Checks: every say()/bark() string in story.js has exactly one line, every line's game_text still
// exists in story.js, ids are unique, and tts_text says the same words as game_text once the
// [tags] are stripped (a TTS clip must match its subtitle).
import fs from 'node:fs';
import path from 'node:path';

const root = path.dirname(path.dirname(new URL(import.meta.url).pathname));
const doc = JSON.parse(fs.readFileSync(path.join(root, 'docs/voice/lines.json'), 'utf8'));
const story = fs.readFileSync(path.join(root, 'src/game/story.js'), 'utf8');
const unq = (s) => s.replace(/\\'/g, "'");

// every spoken string in story.js: say/bark/voice.say/safeSay calls, plus the finale radio table
const calls = [];
for (const m of story.matchAll(/(?:\.say|\.bark|safeSay)\('(\w+)', '((?:[^'\\]|\\.)*)'/g)) calls.push({ kind: m[1], text: unq(m[2]) });
const radio = story.match(/const radio = (\[.*\]);/);
if (radio) for (const m of radio[1].matchAll(/\[\d+, '((?:[^'\\]|\\.)*)'\]/g)) calls.push({ kind: 'dispatch', text: unq(m[1]) });

const errors = [];
const words = (s) => s.replace(/\[[^\]]*\]/g, ' ').toLowerCase().replace(/[^a-z0-9']+/g, ' ').trim();
const ids = new Set();
for (const l of doc.lines) {
  if (ids.has(l.id)) errors.push(`${l.id}: duplicate id`);
  ids.add(l.id);
  const hit = calls.find(c => c.text === l.game_text);
  if (!hit) errors.push(`${l.id}: game_text not found in story.js: "${l.game_text}"`);
  else if (hit.kind !== l.speaker) errors.push(`${l.id}: speaker is "${hit.kind}" in story.js, "${l.speaker}" here`);
  if (words(l.tts_text) !== words(l.game_text)) errors.push(`${l.id}: tts_text words differ from game_text\n    game: ${words(l.game_text)}\n    tts:  ${words(l.tts_text)}`);
  if (!doc.cast[l.speaker]) errors.push(`${l.id}: unknown speaker "${l.speaker}"`);
  if (!doc.scenes.some(s => s.id === l.scene)) errors.push(`${l.id}: unknown scene "${l.scene}"`);
}
for (const c of calls) if (!doc.lines.some(l => l.game_text === c.text)) errors.push(`story.js line has no entry in lines.json: ${c.kind} "${c.text}"`);

// --------------------------------------------------------- recorded clip pack
// The game looks a clip up by the exact game_text string, so a typo in the
// manifest silently reverts exactly ONE line to speech synthesis and nothing
// else notices. Verify the pack against disk and against lines.json.
const manPath = path.join(root, 'assets/voice/manifest.json');
if (fs.existsSync(manPath)) {
  const man = JSON.parse(fs.readFileSync(manPath, 'utf8'));
  const seen = new Set();
  for (const l of doc.lines) {
    const e = man.lines && man.lines[l.id];
    if (!e) { errors.push(`${l.id}: missing from assets/voice/manifest.json`); continue; }
    seen.add(l.id);
    if (e.text !== l.game_text) {
      errors.push(`${l.id}: manifest text differs from game_text — this line would fall back to speech synthesis\n    manifest: ${JSON.stringify(e.text)}\n    game:     ${JSON.stringify(l.game_text)}`);
    }
    const f = path.join(root, 'assets/voice', e.file || '');
    if (!e.file || !fs.existsSync(f)) errors.push(`${l.id}: clip missing on disk: ${e.file}`);
    if (!e.duration) errors.push(`${l.id}: manifest has no duration (the game waits on it)`);
    if (l.max_seconds && e.duration && e.duration > l.max_seconds + 0.05) {
      errors.push(`${l.id}: ${e.duration}s exceeds its hard cap ${l.max_seconds}s`);
    }
  }
  for (const id of Object.keys(man.lines || {})) if (!seen.has(id)) errors.push(`manifest has an unknown line id: ${id}`);
  const packed = Object.keys(man.lines || {}).length;
  if (!errors.length) console.log(`voice: clip pack ok — ${packed} clips, all files present, text matches game_text`);
} else {
  console.log('voice: no assets/voice/manifest.json — the game will use speech synthesis');
}

if (errors.length) { console.error(errors.join('\n')); process.exit(1); }
console.log(`voice: ${doc.lines.length} lines match ${calls.length} spoken strings in story.js`);
if (process.argv.includes('--check')) process.exit(0);

// ---------------------------------------------------------------- SCRIPT.md
const tags = (a) => a.map(t => `[${t}]`).join(' ');
const out = [];
const w = (s = '') => out.push(s);
w('# DEAD AIR: voice-over script');
w();
w('<!-- generated by tools/voice_script.mjs from docs/voice/lines.json; edit the JSON, then run `npm run voice:script` -->');
w();
w(`${doc.lines.length} lines, 5 voices, in play order. The integration contract for the audio files is in [HANDOFF.md](HANDOFF.md); the`);
w('machine-readable version of this script is [lines.json](lines.json).');
w();
w('## How to read a line');
w();
w('```');
w('ID · CHARACTER (channel)');
w('engine: [sounds the game already plays under the line]          <- context only, never bake');
w('> [bake tags] [delivery tags] The words, exactly as subtitled.   <- the TTS prompt (tts_text_full)');
w('after: [sounds the game plays right after the line]');
w('```');
w();
w('| bracket kind | examples | goes into the clip? |');
w('|---|---|---|');
w('| delivery (emotion, volume, breath) | `[shouting]` `[screaming in pain]` `[whispering]` `[long exhale]` `[voice breaking]` | yes, it is how the line is performed |');
w('| bake tags (radio lines only) | `[radio squelch]` `[static]` | optional: bake them and set `radioBaked: true`, or leave them to the engine |');
w('| engine sounds | `[siren]` `[shots]` `[gunfire]` `[rain]` `[heartbeat]` `[TV static]` | **no**, the game plays them, baking doubles them |');
w();
w('The words outside the brackets must stay exactly as written: the subtitle shows them, and the game');
w('finds each clip by that text. `node tools/voice_script.mjs --check` fails if they drift.');
w();
w('## Cast');
w();
w('| id | character | subtitle | channel | voice |');
w('|---|---|---|---|---|');
for (const [k, c] of Object.entries(doc.cast)) w(`| \`${k}\` | ${c.character} | ${c.subtitle} | ${c.channel} | ${c.brief} |`);
w();
w('Channels: **radio** is heard through a police handheld or car radio (band-limited, squelch, a bed of static);');
w('**body-mic** is Halloran himself, the camera is on his chest, so he is always the closest and driest voice;');
w('**distant-outdoor** is shouted across 4 to 7 m of rainy courtyard, the game places it in 3-D at the speaker.');
w();
w('## Pronunciation');
w();
w('| written | say | meaning |');
w('|---|---|---|');
w('| Twenty-one Adam fourteen / Adam fourteen / fourteen | as written | Halloran\'s call sign 21-A-14 (district 21, one-officer car "Adam", beat 14) |');
w('| Keston | KESS-tun | the city; dispatch opens a call with it |');
w('| code three | as written | respond with lights and siren |');
w('| twenty-two fifty Wexley | as written | street number 2250 |');
w('| unit one-C | as written | apartment 1C |');
w('| zero three fourteen | as written | 03:14, 24-hour clock |');
w('| Pell | rhymes with "bell" | Pell Street, where SWAT stages |');
w('| SWAT one | "swot one" | the SWAT team leader\'s call sign |');
w();
for (const s of doc.scenes) {
  const lines = doc.lines.filter(l => l.scene === s.id);
  if (!lines.length) continue;
  w(`## ${s.id} · ${s.title}`);
  w();
  w(`*${s.context}*`);
  w();
  for (const l of lines) {
    const len = `game assumes ${l.est_seconds.toFixed(1)} s${l.max_seconds ? `, **clip max ${l.max_seconds.toFixed(1)} s**` : ''}`;
    const meta = `**When** ${l.trigger} · **Blocking** ${l.blocking ? 'yes, the scene waits for the line' : 'no, it plays over gameplay'} · **Length** ${len}`;
    w(`### ${l.id} · ${doc.cast[l.speaker].character} (${l.channel})`);
    w();
    if (l.engine_sfx.during.length) w(`engine: ${tags(l.engine_sfx.during)}`);
    w();
    w(`> ${l.tts_text_full}`);
    w();
    if (l.engine_sfx.after.length) { w(`after: ${tags(l.engine_sfx.after)}`); w(); }
    if (l.direction) { w(`*${l.direction}*`); w(); }
    w(meta + (l.pronunciation ? ` · **Say** ${l.pronunciation}` : ''));
    w();
  }
}
w('## The whole thing in one block');
w();
w('For a table read: every line with the sounds around it, in brackets.');
w();
w('```');
for (const l of doc.lines) w(`${doc.cast[l.speaker].character.padEnd(24)} ${l.script_text}`);
w('```');
fs.writeFileSync(path.join(root, 'docs/voice/SCRIPT.md'), out.join('\n') + '\n');
console.log('wrote docs/voice/SCRIPT.md');
